name: Bump version and publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  bump-build-publish:
    if: "!contains(github.event.head_commit.message, 'bump version')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine bumpver

      - name: Bump version
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          bumpver update --patch --no-commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: bump version"
          git tag v$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          git push
          git push --tags

      - name: Show new version
        run: python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])" 